name: Run Tests and Publish Results

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  checks: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET 9 (Preview)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests and capture result
        id: tests
        run: |
          dotnet test Tests/Tests.csproj \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=test-results.trx" \
            --results-directory Tests/TestResults
        continue-on-error: true

      - name: Publish test report
        uses: zyborg/dotnet-tests-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_path: Test
          report_name: toolsharp-tests
          report_title: ToolSharp - Test Results

      - name: Fail workflow if tests failed
        if: steps.tests.outcome == 'failure'
        run: |
          echo "❌ Some tests failed. Failing the workflow."
          exit 1