name: Deploy NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Verificar estrutura
        run: ls -la

      - name: Restore dependências
        run: dotnet restore toolsharpSolution.sln

      - name: Build projeto
        run: dotnet build toolsharpSolution.sln --configuration Release --no-restore

      - name: Empacotar NuGet
        run: dotnet pack ToolSharp/ToolSharp.csproj --configuration Release --no-build --output ./nupkg

      - name: Publicar no NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
